name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.LOGIN }}

    - name: Build and Push the Docker image
      run: |
        docker build . --tag ghcr.io/stanremus15/proiectmap:latest
        docker push ghcr.io/stanremus15/proiectmap:latest