name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run:  docker login -u { secrets.DOCKER_USERNAME } --password { secrets.DOCKER_PASSWORD }

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Tag the Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker tag my-image-name:$TIMESTAMP my-dockerhub-username/my-image-name:$TIMESTAMP
        docker tag my-image-name:$TIMESTAMP my-dockerhub-username/my-image-name:latest

    - name: Push the Docker image to Docker Hub
      run: |
        TIMESTAMP=$(date +%s)
        docker push my-dockerhub-username/my-image-name:$TIMESTAMP
        docker push my-dockerhub-username/my-image-name:latest
