name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push the Docker image
      run: |
        docker login --username StanRemus15 --password ${{secrets.GH_PAT}} ghcr.io
        docker build . --tag ghcr.io/stanremus15/proiectmap:latest
        docker push ghcr.io/stanremus15/proiectmap